### ISSUE TITLE
Bibtex, bibitem, or standard acknowledgment?

### ISSUE THREAD

**Issue by DavidMoiseNataf** [sncosmo/extinction#29]
How should one cite this code?

https://extinction.readthedocs.io/en/latest/

Thank you for the excellent and easy-to-use package.

**Comment by DavidMoiseNataf** [comment]
Never mind, I found it:

https://ui.adsabs.harvard.edu/abs/2016zndo....804967B/abstract

**Comment by benjaminrose** [comment]
We will deal with this in #25.
